spring:
  artemis:
    user: artemis
    password: test@123
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: pdp
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/pdp?allowPublicKeyRetrieval=true&useSSL=false
    password: test@123
#  jpa:
#    open-in-view: false
file:
  upload-dir: /home/tamas-balog/Desktop/PDP/pdp/src/main/resources/images
amq:
  queue: pdp